# Generated by Django 2.2.22 on 2022-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sid', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
